### ISSUE TITLE
Delay not working

### ISSUE THREAD

**Issue by thebandit79** [grapeot/IFTTTDelay#5]
Hi, the delay I set up was working fine on the 27-28Sep for the actions I created but has not been working since. Is there an issue with the webhooks action not sending the response back? Regards

**Comment by grapeot** [comment]
Thanks for reporting this. I just checked the system and it looks healthy. I also tested it using my own key and it also worked. Probably you can try again or check the log of your applet to see whether it has some configuration issues?

**Comment by thebandit79** [comment]
ok thanks.
