### ISSUE TITLE
IFTTT receive Webhook never runs

### ISSUE THREAD

**Issue by MrFixIt705** [grapeot/IFTTTDelay#9]
I have tried mutilple times and having reset 1 or not there at all and The IFTTT Webhook never runs. I type the URL directly  into the web browser and your system responds right away. Can you help? Here is the URL I am using.

https://lab.grapeot.me/ifttt/delay?event=STA73FanOFF&t=1&key="My_KEY"

**Comment by grapeot** [comment]
If this is the case, it sounds like the IFTTT Webhook may not be configured properly. Can you paste a screenshot of how you configured the IFTTT? (with the sensitive info masked)

**Comment by MrFixIt705** [comment]
![Make a web Request](https://user-images.githubusercontent.com/113051406/188945940-d6698a5f-43ce-4798-95aa-62ec930b0336.png)
![Recieve  Web Request](https://user-images.githubusercontent.com/113051406/188945944-be8822ad-5930-4fb1-844d-41ba68ea4d93.png)

**Comment by grapeot** [comment]
Thanks for the screenshot! It's helpful. Can you change the method from `post` to `get` and try again?

**Comment by MrFixIt705** [comment]
I changed it to get and it is still not working but we have two other Receive Webhook that is not working either. So I think it may lie with IFTTT. I am going to reach out to them as well.

**Comment by grapeot** [comment]
Thanks MrFixit705. From the log, I can see you issued three more requests. All of them are relayed to IFTTT successfully. I think they should trigger the WebHook. You can check the Webhook's log to double check.

**Comment by MrFixIt705** [comment]
So, I figured it out from a forum post on stackoverflow.com two years ago. If a person is having trouble making the receive web request for the webhook, then they need to go to ifttt.com/maker_webhooks/settings and click reconnect. It will assign a new key that they have to put in the applets and scripts they use it for but fixes the problem none the less.

**Comment by grapeot** [comment]
Ah, this is great to know. Thanks for sharing the learnings. I'm closing the issue for now. But feel free to reopen it if you have further questions.
